import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${geistMono.variable} antialiased m-10`}
      >
        <nav>
          <ul className="flex gap-10 text-3xl">
            <li className=""><Link href="/">Home |</Link></li>
            <li className=""><Link href="/about">About |</Link></li>
             <li className=""><Link href="/blogs">Blogs</Link></li>
          </ul>
        </nav>
        <hr></hr>
        {children}
      </body>
    </html>
  );
}
